version: '3.7'
services:
  db:
    build:
      context: app/database/
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5432:5432"

  bot:
    build: 
      context: app/bot/
    env_file:
      - ./.env
    environment:
      DB_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB} 
    restart: always
    depends_on:
      - db

volumes:
  pgdata: